spring.application.name=backend-spring-boot
spring.data.mongodb.uri=mongodb://root:123@tlas:27017/tlas?authSource=admin
server.port=8080

# Show MongoDB connection attempts in logs
logging.level.org.springframework.data.mongodb.core=INFO
# Show the MongoDB Java Driver logs (connection, server selection, etc.)
logging.level.org.mongodb.driver=INFO
